version: '2.1'
services:
    db:
        image: mysql:5.7
        env_file: .env
        expose:
            - "${DATABASE_PORT}"
        volumes:
            - "db_volume:/var/lib/mysql"
        restart: always

    server:
        build:
            context: ./server
        env_file: .env
        expose:
            - 8182
        ports:
          - "${SERVER_PORT}:8182"
        volumes:
            - "./volumes/server:/home/node/server"
        command: "npm start"
        user: "node"
        working_dir: /home/node/server
        restart: always

    web:
        build:
            context: ./web
        env_file: .env
        expose:
            - 8181
        ports:
            - "${CLIENT_PORT}:8181"
        volumes:
            - "./volumes/web:/home/node/web"
        command: "npm start"
        user: "node"
        working_dir: /home/node/web
        restart: always

volumes:
    db_volume:
        driver: local
